name: Pull request test
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
            node-version: 20.x.x
            cache: npm
<<<<<<< HEAD
=======
      - run: npm ci
>>>>>>> 52a4646f95331b0b31cd5d9e0667c6c7d6499073
      - run: npm run lint
      - run: npm test
      - run: npm run build
      